// Generated by CoffeeScript 1.10.0

/*
 * Copyright (c) 2015 Álan Crístoffer
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

(function() {
  var action, wb;

  wb = null;

  action = '';

  new QWebChannel(qt.webChannelTransport, function(channel) {
    wb = channel.objects.welcome_bridge;
    $(window.trs).each(function() {
      var locale;
      locale = this;
      return $('#' + locale).click(function() {
        window.locale = locale;
        window.update_translation();
        return wb.setLang(locale);
      });
    });
    return wb.lang(function(r) {
      window.locale = r;
      return window.update_translation();
    });
  });

  $(function() {
    var modal_alert, process_error;
    $.material.init();
    $(document).bind('keydown', 'meta+o', function() {
      return $('#load').click();
    });
    $(document).bind('keydown', 'ctrl+o', function() {
      return $('#load').click();
    });
    $(document).bind('keydown', 'meta+n', function() {
      return $('#create').click();
    });
    $(document).bind('keydown', 'ctrl+n', function() {
      return $('#create').click();
    });
    $('#load').click(function() {
      return wb.getExisting(function(res) {
        if (res) {
          $('#actions').css('display', 'none');
          $('#info').css('display', 'block');
          $('#password').focus();
          return action = 'load';
        }
      });
    });
    $('#create').click(function() {
      return wb.getNew(function(res) {
        if (res) {
          $('#actions').css('display', 'none');
          $('#info').css('display', 'block');
          $('#password').focus();
          return action = 'create';
        }
      });
    });
    $('#password').on('keydown', function(e) {
      if (e.which === 13) {
        e.preventDefault();
        if (action === 'load') {
          wb.open($('#password').val(), function(r) {
            $('#password').val('');
            return process_error(r);
          });
        } else if (action === 'create') {
          wb.create($('#password').val(), function(r) {
            $('#password').val('');
            return process_error(r);
          });
        }
        return $(this).val('');
      }
    });
    modal_alert = function(msg) {
      $('#modal-text').html(msg);
      return $('#alert-modal').modal('show');
    };
    process_error = function(error) {
      switch (error) {
        case 'Success':
          return wb.close();
        case 'DoesntExistAndCreationIsNotPermitted':
          return modal_alert(window.tr("DoesntExistAndCreationIsNotPermitted"));
        case 'CantCreateCryptoObject':
          return modal_alert(window.tr("CantCreateCryptoObject"));
        case 'CantOpenStoreFile':
          return modal_alert(window.tr("CantOpenStoreFile"));
        case 'CantOpenFile':
          return modal_alert(window.tr("CantOpenFile"));
        case 'CantWriteToFile':
          return modal_alert(window.tr("CantWriteToFile"));
        case 'FileTooLarge':
          return modal_alert(window.tr("FileTooLarge"));
        case 'NoSuchFile':
          return modal_alert(window.tr("NoSuchFile"));
        case 'PartCorrupted':
          return modal_alert(window.tr("PartCorrupted"));
        case 'WrongCheckSum':
          return modal_alert(window.tr("WrongCheckSum"));
        case 'FileAlreadyExists':
          return modal_alert(window.tr("FileAlreadyExists"));
      }
    };
    return $('#cancel').click(function() {
      $('#password').val('');
      $('#actions').css('display', 'block');
      return $('#info').css('display', 'none');
    });
  });

}).call(this);
